### ISSUE TITLE
Unicode vs. ANSI In Simba.

### ISSUE THREAD

**Issue by Brandon-T** [MerlijnWajer/Simba#120]
Unknown identifier '' at line 339

^ Those are unicode vs. ANSI errors.

See here for why Simba needs the code-editor updated OR all strings need changing to WStr/WChars:

http://villavu.com/forum/showthread.php?t=84679

This is happening a lot more often than never.

**Comment by MerlijnWajer** [comment]
Is this still relevant?

**Comment by Brandon-T** [comment]
It doesn't seem to be happening anymore. The includes don't seem to be having this problem at all actually. Not sure what changed but whatever it is, it's a good thing.

The only issue I've seen lately with charsets is the wide-string or unicode-string in Simba. It would be nice to have a UTF8ToUTF16 and vice-versa function in Simba. Simba cannot print UTF16 characters. It can print UTF8 characters perfectly fine :D Which IMO is the best choice (UTF8 everywhere ftw). I still would like a conversion function though (IF it's not too much work or too much to ask):

See:
https://villavu.com/forum/showthread.php?t=111729&p=1327439#post1327439

I created my own via a plugin but it's something to think about (Simba support without plugins) I guess?

Another irrelevant issue is that Simba cannot print strings containing a null character but again, irrelevant to this issue.

**Comment by MerlijnWajer** [comment]
Right, but please file a different bug/issue for those requests/bugs. I'll close this issue then; thanks.
