### ISSUE TITLE
getFile on file names with unicode characters such as æøå returns ? instead of the unicode character.

### ISSUE THREAD

**Issue by Zyt3x** [MerlijnWajer/Simba#182]
getFiles(path, 'ext'); on a path where I have i.e "ææøøåå.ext" returns "??????.ext", making it impossible to read the actual file without know it's actual filename.

**Comment by JohnPeel** [comment]
@riwu , this has been merged properly, correct?

**Comment by nielsAD** [comment]
Yes, can be reopened if the problem persists.
