### ISSUE TITLE
Compile error on Ubuntu Linux

### ISSUE THREAD

**Issue by JacobHacker** [MerlijnWajer/Simba#216]
In mmlpsthread:
```
procedure lp_CurrThreadID(Params: PParamArray; Result: Pointer); lape_extdecl
begin
{$IFDEF WINDOWS}
  PPtrUInt(Result)^ := GetCurrentThreadID();
{$ELSE}
  {$IFDEF LINUX}
  PPtrUInt(Result)^ := TThreadID(pthread_self);
  {$ELSE}
  PPtrUInt(Result)^ := GetThreadID();
  {$ENDIF}
{$ENDIF}
end;     
```

Specifically this line:
```
PPtrUInt(Result)^ := TThreadID(pthread_self);
```
~/src/Simba/Units/MMLAddon/mmlpsthread.pas(1302,46) Error: Identifier not found "pthread_self"

Thoughts?

I still don't realize how Gentoo will compile it easily, and Ubuntu is taking forever to get working.

**Comment by MerlijnWajer** [comment]
Is this still an issue? I presume it is not.

**Comment by JohnPeel** [comment]
No clue, my builds (x64, x86, ARM) are all fine, but it might be a laz/fpc version issue. We should set a specific version and force all devs/users (that compile) to use it

**Comment by JohnPeel** [comment]
I'm going to assume the lack of updates means you've figured it out. We also cannot reproduce the issue.
