### ISSUE TITLE
Disable Simba startup misc

### ISSUE THREAD

**Issue by riwu** [MerlijnWajer/Simba#297]
https://github.com/MerlijnWajer/Simba/issues/293

-Option (stored in settings.xml?) to disable auto font loading (only load them manually in script with LoadFont()).
(Added by JohnPeel: https://github.com/MerlijnWajer/Simba/issues/293#issuecomment-55649018 -- i will test later)

-option to disable extension loading (http://puu.sh/bCkO1/4faa2f10ca.png) and the Simba news
(https://github.com/MerlijnWajer/Simba/issues/293#issuecomment-55964819)

Any other thing simba loads that isnt compulsory?

**Comment by riwu** [comment]
other than the font loading, the other features are very minor optimizations that i'm probably the only one interested, so i guess i will just edit them for my private use instead

**Comment by MerlijnWajer** [comment]
I'm happy to look at pull requests if you end up writing it.
