### ISSUE TITLE
64bit Simba Tools > settings error

### ISSUE THREAD

**Issue by riwu** [MerlijnWajer/Simba#304]
Just a minor bug:
Clicking Tools > settings in 64bit simba pops up the error message:
http://puu.sh/bRQQ3/1631bc40d2.png

Program exception! 
Stacktrace:

Exception class: EAccessViolation
Message: Access violation
  $000000000069D918
  $0000000000420879
  $000000000041F88A
  $000000000040DE6E
  $0000000000596030
  $0000000000421953
  $00000000005A411D
  $0000000000593489
  $00000000005933A8
  $0000000000425B78
  $00000000005918AA
  $00000000005AFF08
  $00000000005ACBA3
  $000000000041F3F9
  $0000000000424422
  $0000000000426073
  $000000000043FD9B
Simba Version: 1100

**Comment by Olly-** [comment]
This is because there is no pascal script in 64-bit simba and there is no {IFDEF} around the pascal script parts.

Super easy to fix, though If you use 64-bit simba your lape is 10x slower.

**Comment by MerlijnWajer** [comment]
tpho

**Comment by riwu** [comment]
Fixed with https://github.com/MerlijnWajer/Simba/pull/363
