### ISSUE TITLE
type . and crash still not fixed

### ISSUE THREAD

**Issue by riwu** [MerlijnWajer/Simba#309]
Just got crashed typing . after a record variable.
Using Simba 1.1.0 (latest) and 64 bit.

Program exception! 
Stacktrace:

Exception class: EAccessViolation
Message: Access violation
  $000000000088EC24
  $00000000006A7DCF
  $00000000006A7DCF
  $00000000006A743F
  $0000000000686112
  $0000000000685484
  $000000000064C020
  $00000000006494DC
  $000000000063F619
  $0000000000597A24
  $0000000000594BE9
  $000000000055057D
  $000000000054D296
  $00007FF8852B2434
  $000000000042F533
  $000000000042FA02
  $000000000045979E
Simba Version: 1100

**Comment by MerlijnWajer** [comment]
We could try to provide Simba builds with debug information, @JohnPeel . If you know how to do it, I can easily edit/change the l0.lt autobuilders to include debugging information.

**Comment by JohnPeel** [comment]
@MerlijnWajer We could, iirc it's an option to fpc, or we could switch to lazbuild (and use profiles [release and debug])

@riwu The released binaries are stripped of debugging information, compiling it yourself will leave that information and the stack trace will have much more useful data (file and line number)

**Comment by JohnPeel** [comment]
The current RC build of 1.2.0 has debugging symbols, can you reproduce your stacktrace with that build?

**Comment by WarPie** [comment]
Here is a little something:
```console
Codeinsight[CheckIt]: Access violation
Codeinsight[CheckIt]: Access violation
TApplication.HandleException Access violation
  Stack trace:
  $0083CED0  TDECLARATIONLIST__GETCOUNT,  of C:/Simba/Workspace/Simba - GIT/Units/Misc/v_ideCodeParser.pas
  $0061E4E5  CHECKINCLUDE,  line 1703 of C:/Simba/Workspace/Simba - GIT/Units/Misc/v_ideCodeInsight.pas
  $0061E4E5  CHECKINCLUDE,  line 1703 of C:/Simba/Workspace/Simba - GIT/Units/Misc/v_ideCodeInsight.pas
  $0061E4E5  CHECKINCLUDE,  line 1703 of C:/Simba/Workspace/Simba - GIT/Units/Misc/v_ideCodeInsight.pas
  $0061DDAC  TCODEINSIGHT__FILLSYNCOMPLETIONPROPOSAL,  line 1782 of C:/Simba/Workspace/Simba - GIT/Units/Misc/v_ideCodeInsight.pas
  $005FEA05  TSCRIPTFRAME__SYNEDITPROCESSUSERCOMMAND,  line 405 of framescript.pas
  $005FE08C  TSCRIPTFRAME__SYNEDITCOMMANDPROCESSED,  line 262 of framescript.pas
  $005C8480  TCUSTOMSYNEDIT__DOONCOMMANDPROCESSED,  line 6775 of synedit.pp
  $005C57DD  TCUSTOMSYNEDIT__COMMANDPROCESSOR,  line 6197 of synedit.pp
  $005B9B38  TCUSTOMSYNEDIT__UTF8KEYPRESS,  line 2849 of synedit.pp
  $0053E1BB  TWINCONTROL__DOUTF8KEYPRESS,  line 5895 of ./include/wincontrol.inc
  $0053C440  TWINCONTROL__INTFUTF8KEYPRESS,  line 4943 of ./include/wincontrol.inc
  $0050435F  HANDLEUNICODECHAR,  line 1072 of ./win32/win32callback.inc
  $00501C6E  WINDOWPROC,  line 1229 of ./win32/win32callback.inc
  $755C62FA
  $755C6D3A
  $755C77C4

Something went wrong...
```

**Comment by JohnPeel** [comment]
Ah, ok, I can look into fixing it in the next couple of days (Hopefully).

Seeing as it's just a getCount, it probably is a thread syncing issue.

**Comment by nielsAD** [comment]
I looked into this. For ctrl+click, param hints, and code completion, a new `TCodeInsight` instance is created on every use. This all happens in the main thread. For the function list, parsing is offloaded to another thread.

Now, `TCodeInsight` is pretty indifferent about threads **except** for a global include cache. There appear to be some useless critical sections whenever a new include is appended to the cache, but there's not guard around removal (`DeleteIncludeBufferIndex`). We could fix either the critical sections (basically we should guard the entire `GetIncludeBuffer` function) or we could use a thread local include cache (`threadvar`). The trace @WarPie posted is probably related to what I describe.

In other thread news: I can't really follow what's happening thread-wise in [os_linux.pas](https://github.com/MerlijnWajer/Simba/blob/master/Units/MMLCore/os_linux.pas). Especially the `{ XXX FIXME TODO O GOD WTF }` parts.

**Comment by WarPie** [comment]
@JohnPeel : Recreate with Win32:
- Get SimbaExt_beta from http://slacky.info/downloads/SimbaExt_beta.rar
- Extract to SimbaExt_beta in includes folder
- Start Simba
- Write:
```pascal
{$I SimbaExt_beta/SimbaExt.simba}
begin
end.  
 ```
- from functionlist open `Includes/Core.pas`
- Return to the script tab again
- within `begin` `end` block write `se.`
