### ISSUE TITLE
Taking much longer to start up simba

### ISSUE THREAD

**Issue by riwu** [MerlijnWajer/Simba#310]
It takes much longer to start up recent versions of simba. (both 32 and 64bit)
Sometimes it got stuck here for several seconds (sometimes over 10s) before starting the GUI
http://puu.sh/bYmlj/223c157e10.png

Any idea what change is causing it?

**Comment by riwu** [comment]
Figured out the cause:
https://github.com/MerlijnWajer/Simba/blob/master/Units/Synapse/ssl_openssl_lib.pas#L1857
_RandScreen is the sole culprit of the delay.

Reason why it didnt occur prior to win8 is because at L1735, both SSLLibHandle and SSLUtilHandle are 0, so _RandScreen doesn't get executed at all.

**Comment by MerlijnWajer** [comment]
Is there a PR to fix this? We can just not call randscreen - it's stupid to call it.
