### ISSUE TITLE
UTF8 to UTF16 conversion support

### ISSUE THREAD

**Issue by Brandon-T** [MerlijnWajer/Simba#338]
Lately, I've seen one issue with charsets when using the wide-string or unicode-string in Simba. It would be nice to have a UTF8ToUTF16 and vice-versa function in Simba. Simba cannot print UTF16 characters. It can print UTF8 characters perfectly fine :D Which IMO is the best choice (UTF8 everywhere). However, I would like to request a conversion function though (IF it's not too much work or too much to ask):

See (for example):
https://villavu.com/forum/showthread.php?t=111729&p=1327439#post1327439

I created my own via a plugin but it's something to think about (Simba conversion support without plugins).

**Comment by Olly-** [comment]
@Brandon-T What you want is http://lazarus-ccr.sourceforge.net/docs/rtl/system/utf8decode.html (and encode) right?

**Comment by Brandon-T** [comment]
@Olly- yep.

**Comment by R030t1** [comment]
@Brandon-T: Where are you encountering UTF-16?

Based on a lot of reading I did w.r.t. Window's Unicode implementation it is best to avoid it completely and to only use it to interact with the OS where necessary. Hopefully this means the LCL would take care of everything, meaning Simba should only ever see UTF-8 data.

**Comment by Brandon-T** [comment]
@R030t1 Simba will "never" see only UTF-8 data when dealing with Runescape because it is written in Java and it uses UTF-16. So for OpenGL when I originally wrote it, I was feeding the characters directly to Simba and hoped that Simba could print them. It could NOT print them because UTF-16 characters typically begin with a null-terminator character: "\0".

So I had to convert them to UTF-8 for Simba to correctly read and print them from within the plugin itself as Simba doesn't support it or have a function to convert to it. You cannot avoid UTF-16 on Windows because certain characters like Chinese or Japanese or Arabic consist of mostly UTF-16 characters. Even for UTF-8 supported characters such as Russian, it will NOT work:

https://stackoverflow.com/questions/21370710/unicode-problems-in-c-but-not-c

Must be converted to Wide-Char and then printed.

**Comment by R030t1** [comment]
@Brandon-T: Okay, that's understandable. If possible it would probably be best to have any plugins interfacing with Java encode strings as UTF-8.

http://utf8everywhere.org/ gives a good outline of what is wrong and how it can be solved. It looks like this issue report was going in that direction, but I just want to mention it specifically.

**Comment by MerlijnWajer** [comment]
It would indeed seem that you need to encode the text to whatever Simba expects, so UTF-8. That's a standard procedure for many languages.

**Comment by R030t1** [comment]
So I don't know the best way to evaluate the Simba source, but some changes might be necessary if they aren't already in place: http://wiki.lazarus.freepascal.org/Unicode_Support_in_Lazarus#With_.7B.24codepage_utf8.7D_or_compilerswitch_-FcUTF8. With those options and UTF-8 source assignment of literals happens properly and the default types seem to be compatible using UTF-8 by default. On the FreePascal side conversions to and from UTF-8/UTF-16 can be carried out by casting or explicit calls to class methods; these calls and the corresponding types would need to be made available in LAPE.

I have this vague notion that it may be hard for some people to edit the source code on Windows if it is UTF-8, but most third party editors make up for deficiencies in the OS.
