### ISSUE TITLE
Memory Allocation Scheme for plugins.

### ISSUE THREAD

**Issue by Brandon-T** [MerlijnWajer/Simba#340]
Plugin system memory allocation scheme.

Can we add something to the current plugin system such as a callback for allocating from Simba's managed memory pool?

For example:

```
procedure allocator(var Ptr: Pointer; size: Integer; element_size: Integer);
type PInt = ^Integer;
var
  NewSize: Integer;
begin
  NewSize := Size * element_size;
  Inc(NewSize, sizeof(Integer) * 2);

  Ptr := AllocMem(NewSize);
  PInt(Ptr)^ := 1;
  Inc(PInt(Ptr));
  PInt(Ptr)^ := Size - 1;
  Inc(PInt(Ptr));
end;
```

Then when the plugins are initialised it would do: `plugin.setMemoryAllocators(@allocator);`

The above allocator was written based off of (Lape's SetLength function): https://github.com/SRL/Lape/blob/master/lpvartypes_array.pas#L205

This way, plugins can allocate data (TIntegerArray, et al) that can be used in Simba without having to hack it apart and add reference counting and free memory manually. Yes we can do this from scripts, but it's tedious to ask users to pass an allocation function.

Even if we cannot do the above, being able to just allocate a memory compatible array with Simba would be nice! See below:

```
//Stupid dummy function to pass to Natify ={

Function SimbaAlloc(Size: Integer): Pointer;
begin
  Result := AllocMem(Size);
end;

var
  I: Integer;
  TIA: TIntegerArray;
begin
  SetAllocator(Natify(@SimbaAlloc)); //would be nice NOT to have to do this.. Would also be nice if we didn't have to create a dummy script function as well.. Can just do @AllocMem..

  for I := 0 to 500 do
  begin
    TIA := trueRandomIntArray(500, 900, 500); //allocated from a plugin.
    writeln(TIA);
  end;
end;
```

But if Simba did any of these upon initialising the plugins, it would go a very long way! I've tested all of this.

**Comment by nielsAD** [comment]
If you export `procedure SetPluginMemManager(MemMgr : TMemoryManager)` in your plugin, Simba will call it upon initialization. `TMemoryManager` holds references to all the methods needed for memory management. If you write your plugin in FPC, `SetMemoryManager` is all that's needed to use Simba's memory manager.

Sorry for the late reply!

**Comment by Brandon-T** [comment]
@nielsAD This only works for Pascal plugins though. I realised that after writing it all out. http://pastebin.com/S65R0MAW

There's no way to set memory manager for plugins written in any other languages.

**Comment by nielsAD** [comment]
Because of the calling convention?

**Comment by MerlijnWajer** [comment]
I don't think it is impossible, as I recall doing it from C several years ago. As you all understand, I guess, anything that you want to pass to FPC will need to be allocated using the memory manager.

I guess I'm also not sure why you think it wouldn't work - as Niels said, calling convention comes to mind, but that is easily fixed with a wrapper, if the calling convention is not available in the host language?

**Comment by Brandon-T** [comment]
Not because of the calling convention. Because plugins written in other languages cannot call "SetMemoryManager" or "GetMemoryManager". The only way to do it is to build a static library wrapper in FPC that will call these functions for you then link your code against the wrapper and call the wrapper functions.

There's also Structural differences.. IE: Struct alignment, padding. The TMemoryManager isn't a packed record. The calling convention for all of its functions are "register" and languages such as C have CDECL or STDCALL instead. I guess a wrapper would work but it'll have to be a Pascal wrapper.

**Comment by MerlijnWajer** [comment]
Why? We can simply export the TMemoryManager is a more friendly format from Simba. We don't need another library for that, and if we did that, why would it need to be static? I don't see it as a problem to ship a simple simba-plugin-helper.so with Simba, but I have a preference for just fixing this problem in Simba.

Of course other languages cannot call "(G|S)etMemoryManager", but they can explicitly call the memory manager functions for data that they want to pass to FPC, and for other data, they just use their own allocator.

**Comment by ollydev** [comment]
Added in e6daa6179fe9f29f9ab3da53002d8711269d8c89

Have a export named `SetPluginSimbaMemoryAllocators` the following record is passed:
```pascal
TSimbaMemoryAllocators = packed record
    GetMem: function(Size: PtrUInt): Pointer; cdecl;
    FreeMem: function(Ptr: Pointer): PtrUInt; cdecl;
  end;
```

**Comment by MerlijnWajer** [comment]
@ollydev - can we close this then?
