### ISSUE TITLE
[Lape] Build new libffi for windows x64 and x86

### ISSUE THREAD

**Issue by WarPie** [MerlijnWajer/Simba#346]
We need the latest version of libFFI built, and shared somewhere.

- Not a directly related to Simba, but will be needed for Lape soon enough.

**Comment by MerlijnWajer** [comment]
I build the latest libffi here: http://nala.villavu.com/downloads/var/

Static and dynamic versions available. Please test.

**Comment by nielsAD** [comment]
The dynamic versions work. Haven't tested the static versions yet.

**Comment by MerlijnWajer** [comment]
Thanks. Assigning it to you, that is, if you want to test the static versions. Otherwise, feel free to either close it or reassign to me.

**Comment by nielsAD** [comment]
They appear to work with 1.2RC2 :+1:Thanks!
