### ISSUE TITLE
[IDE] Broken Documentation Link [keyboard, mouse, socket, crypto, ...]

### ISSUE THREAD

**Issue by Turbine1991** [MerlijnWajer/Simba#350]
Most of the documentation links in the Simba IDE return a 404 page like this: http://docs.villavu.com/simba/scriptref/keyboard.html#presskey

**Comment by MerlijnWajer** [comment]
I am working on fixing this (server migration), hopefully it'll be solved today

**Comment by Turbine1991** [comment]
Thank you once again. It was a brilliant idea to integrate this into the ide. Simba lets me write code nearly twice as fast as Scar.

**Comment by MerlijnWajer** [comment]
Hm. Seems I still didn't do it -- damnit. Putting it high on my list!

**Comment by Turbine1991** [comment]
You seem rather bogged down, I appreciate the openness of Simba!

**Comment by MerlijnWajer** [comment]
Just keep bugging me - I forget sometimes. I will need about 15 minutes to do it, so please, do (keep) reminding me. I only found this url somewhere deep in my 'todo' notes.

**Comment by MerlijnWajer** [comment]
I think I have fixed it! See docs.wizzup.org -- docs.villavu.com may already work depending on when the DNS is migrated.

**Comment by MerlijnWajer** [comment]
See http://docs.wizzup.org/simba/referencescript.html#scriptref

**Comment by MerlijnWajer** [comment]
See http://docs.wizzup.org/simba/referencescript.html#scriptref

**Comment by MerlijnWajer** [comment]
Actually -- the issue is seperate from all docs being down. But at least the docs are up again. Now we just need to fix the link.

**Comment by MerlijnWajer** [comment]
This seems to be mostly changing the documentation filenames names to match the ones in Units/MMLAddoc/(LP/PS)Inc/Wrappers.

**Comment by MerlijnWajer** [comment]
Or rather, the actual sections.

**Comment by Turbine1991** [comment]
It's all good, 8 consecutive responses.

**Comment by JohnPeel** [comment]
@MerlijnWajer Update?

**Comment by nielsAD** [comment]
We need to update documentation https://github.com/MerlijnWajer/Simba/tree/master/Doc/sphinx/scriptref to match the function list categories / functions. It will would be nice to be able to generate this list/documentation automatically.

For milestone 1.2, I suggest we at least put up placeholder files for categories that do not exist yet, so people do not get a `404`. Filling in missing documentation is less urgent, in my opinion.

Categories:

- [ ] `other`
- [ ] `dtm`
- [ ] `bitmap` (currently: `bitmaps`)
- [ ] `math`
- [ ] `color` (currently: `colourfinding`)
- [ ] `color conversion` (currently `colourconverting`)
- [ ] `crypto`
- [ ] `files`
- [ ] `web`
- [ ] `socket`
- [ ] `mouse` (currently `mouseandkeyboard`)
- [ ] `keyboard` (currently `mouseandkeyboard`)
- [ ] `ocr`
- [ ] `settings`
- [ ] `string`
- [ ] `tpa`
- [ ] `window`
- [ ] `lape`

**Comment by JohnPeel** [comment]
I could also add the ability to have the document link use an alternative section name.
