### ISSUE TITLE
[Documentation] Example for function "FindAndSetTarget" uses non-existant string comparison function

### ISSUE THREAD

**Issue by Turbine1991** [MerlijnWajer/Simba#351]
The example employs the use of "StartsWith" - which is a non-existent function.

Page: http://docs.villavu.com/simba/scriptref/window.html#setdesktopasclient

Offending code:
```
function FindAndSetTarget(TitlePrefix: String; SetAsTarget: Boolean): Boolean;
var
  T: TSysProcArr;
  I: Integer;
begin
  T:= GetProcesses();
  for I := 0 to high(T) do
    if StartsWith(TitlePrefix, T[i].Title) then //THIS LINE!
    begin
      Result := True;
      if SetAsTarget then
      begin
        SetTarget(T[i]);
        ActivateClient;
      end;
    end;
end;     
```

**Comment by MerlijnWajer** [comment]
Thanks for the report - fixed with Riwu's commit. The docs are usually autobuilt every hour - but due to some server outage it will take a bit longer than usual.

**Comment by Turbine1991** [comment]
Thank you for your prompt feedback.

I couldn't find a simple equivelant, regex was probably the closest.
