### ISSUE TITLE
TComponent.GetComponent(index: integer) should be a function.

### ISSUE THREAD

**Issue by ObscuritySRL** [MerlijnWajer/Simba#355]
In:
Simba/Units/MMLAddon/LPInc/Classes/miniLCL/lplclsystem.pas

Line 1077:
https://github.com/MerlijnWajer/Simba/blob/d737b95664d0966a58c55a678a526abe3dbb90b9/Units/MMLAddon/LPInc/Classes/miniLCL/lplclsystem.pas#L1077

Should be:
```
addGlobalFunc('function TComponent.GetComponent(index: integer): TComponent;', @TComponent_Components); 
```

**Comment by MerlijnWajer** [comment]
This is fixed in 598f55d I believe.
