### ISSUE TITLE
[Linux] Crash on open

### ISSUE THREAD

**Issue by Harrierr** [MerlijnWajer/Simba#379]
After #378 simba on linux will instantly crash once opened. Compiling a version of simba before this commit allows for it to open and function fine. 
""Pango:ERROR:pango-layout.c:3916:pango_layout_check_lines: assertion failed: (!layout->log_attrs)""
libpango-1_0_0-32bit version 1.36.8-2.2

**Comment by WarPie** [comment]
I just compieled and tested, it works fine for me. I guess you have your old `settings.xml` file, that might be the cause of it, as that commit you liked to added another field in that file.

**Comment by nielsAD** [comment]
An unassigned result caused new settings not to be written correctly (this was also a problem with deleted `settings.xml`). Not sure if this is related to this issue, as the error message @Harrierr shows does not seem about settings.

**Comment by nielsAD** [comment]
As both @WarPie and I cannot reproduce this, I've removed the urgent tag and milestone for now.

**Comment by nielsAD** [comment]
Appears to be related to the function list. Hiding it on start prevents the error. Showing the function list once Simba is started generates the error immediately.

**Comment by Harrierr** [comment]
Fixed in @nielsAD  commit
