### ISSUE TITLE
Form Editor does not work correctly

### ISSUE THREAD

**Issue by nielsAD** [MerlijnWajer/Simba#383]
- [x] Generated code does not compile
- [x] Icons on speed buttons are shifted (see https://imgur.com/a/9Xkau)
- [ ] I can't change height for some components (e.g. ComboBox, EditBox)
- [x] I can't delete elements in the form editor (not with delete button, not with right click menu)

@CynicRus

**Comment by nielsAD** [comment]
TRadioButton is not exported, so doesn't work yet as well.

**Comment by JohnPeel** [comment]
TRadioButton should be hidden for now >..>

**Comment by R030t1** [comment]
@nielsAD: Can you explain what you mean by "I can't change height for some components?" In the Lazarus form editor some of the listed components won't change their vertical height when being drug, and do not want to be set as anything other than their default.

**Comment by nielsAD** [comment]
That might explain it then! However, that is probably because of the autosize property of the component, which we might want to expose in the form editor as well.
