### ISSUE TITLE
Find previous

### ISSUE THREAD

**Issue by JohnPeel** [MerlijnWajer/Simba#391]
https://github.com/MerlijnWajer/Simba/blob/master/Projects/Simba/simbaunit.pas#L2222

**Comment by nielsAD** [comment]
Added in eab562f4bb8016b80538b3cd994c48bf1766e9db. Could you check if the search behaviour is still the same for the other things as well?

**Comment by JohnPeel** [comment]
I'll look into testing it later today, thanks for adding it! =)

**Comment by JohnPeel** [comment]
Ok, seems to work as expected! Although, I don't like placement of the buttons, think they should line up with the input box?

**Comment by nielsAD** [comment]
Should be fixed with 12880c8d0d5d6101c73836efe7e46b939b025be2. Not sure if this is related to Linux or a newer version of Lazarus.
