### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by marcelomelofreitas** [MerlijnWajer/Simba#446]
What version of freepascal and lazarus should I use to compile simba? I tried with one last version of many and many errors in synedit, I tried with a version 2.6.4 of freepascal and many UTF8 errors?

**Comment by KeepBotting** [comment]
Simba 1.2 (revision 1206, master branch) can be compiled with either FPC 2.6.4 or FPC 3.x, and should be compiled with Lazarus 1.6.2.

Simba 1.3 (revision 1300, fpc-3.0 branch) should be compiled with FPC 3.x and Lazarus 1.8.4.

For extensive documentation on the build process, I have a thread over at the community forums: https://villavu.com/forum/showthread.php?t=118324

**Comment by JohnPeel** [comment]
Closing as question was answered.
