### ISSUE TITLE
Win7 DPI combatability

### ISSUE THREAD

**Issue by saml1991** [MerlijnWajer/Simba#498]
When setting the windows setting:Control Panel\All Control Panel Items\Display to 150% Simba sees the screen wrong. This can be seen when selecting a client - it doesn't get the screen size/position right. It also shows when using mouse functions in SRL, the mouse starts from a different location to where it currently is when it moves.

I know this is a niche issue, but I like to use Simba while actively playing a web browser game to semi automate the clicking intense parts. I haven't had success in trying different web browsers and forcing DPI. I'd love to hear if there are any other workarounds (maybe adding a formula to getmousepos to account for DPI?).

**Comment by saml1991** [comment]
Hi All, an update to this I have found a workaround!

In windows control panel>display>set custom text size (DPI) ticking 'Use windows xp style dpi scaling' fixes the client selector and correct mouse positions. 

https://wiki.freepascal.org/High_DPI 

After changing this setting, the coordinates at the bottom of the window get cut off and the function list title

![image](https://user-images.githubusercontent.com/54473694/64492559-fcbc2380-d26c-11e9-9e4a-3e91f688ac5f.png)

**Comment by ollydev** [comment]
Cool! I tried this a while ago and noticed it fixed the system calls, but when moving Simba from a scaled display to a no scaled display it would crash Simba badly (a LCL bug with a resizing loop) Does this still happen?

**Comment by saml1991** [comment]
I'm sorry ollydev - I only have 1 screen (my TV) to try this on. I've been using it happily as is since discovering the workaround though.

**Comment by ollydev** [comment]
Fixed in the upcoming simba1500. Toolbar images are messed up, but that's on Lazarus.

![win7](https://user-images.githubusercontent.com/3413206/170629404-87d53cd3-fc9a-4545-ac90-4fc06a92abcc.png)
