### ISSUE TITLE
Simba 1400

### ISSUE THREAD

**Issue by ollydev** [MerlijnWajer/Simba#503]
@MerlijnWajer 

I'm proposing merging my Simba 1400 [branch](https://github.com/ollydev/Simba/tree/simba1400).

First, I propose this is merged in with a clean history. Early on I gave up trying to keep a clean and understandable history. Simba's source was so interlaced and not very modularized I would end up rewriting a component which was also required modifications in 5 other files and the process repeats.

Also, every file has been at least:
- Renamed: Files have been prefixed with `simba.`
- Moved:  There are now two seperate projects & repository has been cleaned.
- Modified: Licence was updated.

So regardless the history is changing a lot. I actually think starting with a clean history might be better providing the previous verisons are branched.

----
### Out of process scripts

The biggest change is that scripts are now ran in their own process, this means there are now two main Lazarus projects:
- Simba: The IDE
- SimbaScript: The process which runs scripts

When `Simba` project is built the `SimbaScript` project is automatically built with the binary being written into a resource file which Simba will include and extract at runtime, this keep Simba portable.

Scripts can also be executed on the command line:
```
Options:
  --run:          Runs the given script
  --compile:      Compiles the given script

  --target:       Window handle to target. Defaults to Desktop
  --apppath:      Defaults to SimbaScript.exe location
  --datapath:     Defaults to AppPath/Data
  --pluginpath:   Defaults to AppPath/Plugins
  --fontpath:     Defaults to AppPath/Fonts
  --includepath:  Defaults to AppPath/Includes

Example:
  SimbaScript.exe --run "script.simba"
```

The script API has not changed from Simba 1300.

----

### Other notable changes

- MacOS & AArch64 support.
- Hi-DPI support on Windows for both Simba IDE and scripts.
- Dockable components, drag components by their header to detach, attach, and rearrange. 
- Script formatter.
- Script association on Windows.
- Run with debugging which shows a live log of the scripts function calls.
- Code tools have all been rewritten, optimized & support lapes syntax better.
- Mouse extra buttons will now traverse through editor history. History is added on click & on tab change.
- New settings form & improved customization.
 - Debug image improvements support zooming (ctrl + scroll) & double clicking will print out click coordinate.

Thanks to @KeepBotting for testing aarch64 on his pinebook. And @Brandon-T for testing and programming macOS.

Binaries can be found [here](https://github.com/ollydev/Simba/releases/tag/autobuild-simba1400) if you're interested.

----
Windows:

![img](https://i.imgur.com/11kzk25.png)

MacOS:

![img](https://i.imgur.com/O16Zq4A.png)

Editor Color Settings:

![img](https://i.imgur.com/CaN5XNo.png)

Editor Font Settings:

![img](https://i.imgur.com/nFYvuKX.png)

Debugger:

![img](https://i.imgur.com/XtyYou1.png)

Auto Complete:

![img](https://i.imgur.com/74e3Tnx.png)

Docking:

![img](https://i.imgur.com/8xIL9Kj.png)

**Comment by ghost** [comment]
Where is --pause?

**Comment by slackydev** [comment]
This is awesome. Really great major changelog you are showing.
@MerlijnWajer make it happen

**Comment by MerlijnWajer** [comment]
@ollydev - is the PR up to date with your latest changes?
