### ISSUE TITLE
Crashes with the following test code

### ISSUE THREAD

**Issue by JuanCarlosMagana** [MerlijnWajer/Simba#504]
Trying to run the following script crashes:

program Delphi_in_a_Box;

const mys = 'CODESIGN!';
var i: byte;
 inFrm: TForm;

begin
  inFrm:= TForm.create(nil)
  for i:= 1 to 3 do
    writeln(intToStr(i) + ' aloha from CoreCode');
  with inFrm do begin
    position := poScreenCenter;
    color:= clred;
    caption:= 'Delphi in a Box'
    show;
  end;  
  showmessage('the boX rocks ' + mys)
end.

**Comment by slackydev** [comment]
Simba do not use Delphi. The programming language is called Lape, which is a different language. The idea's are similar, but not the same.
```pascal
program THIS_IS_NOT_Delphi_in_a_Box;

const
  mys = 'CODESIGN!';
var
  i: byte;
  inFrm: TForm;
begin
  inFrm.Init(nil);
  for i:= 1 to 3 do
    writeln(intToStr(i) + ' aloha from CoreCode');

  with inFrm do begin
    SetPosition(poScreenCenter);
    SetColor($FF);
    SetCaption('Delphi in a Box');
    Show;
  end;
end.
```
Your script makes no sense to me tho, just does several things, and ShowMessage will never be executed because of the form created.
```pascal
program THIS_IS_NOT_Delphi_in_a_Box;

const
  mys = 'CODESIGN!';
var
  i: byte;
  inFrm: TForm;
begin
  inFrm.Init(nil);
  for i:= 1 to 3 do
    writeln(intToStr(i) + ' aloha from CoreCode');

  ShowMessage('the boX rocks ' + mys)
end.
