### ISSUE TITLE
Simba 1.5 code tools issues.

### ISSUE THREAD

**Issue by CelularBat** [MerlijnWajer/Simba#508]
Hi, 
I'm testing Simba 1.5 and I'm amazed by the improvement and how neat it is. I used to use my own library with tons of overloads of basic functions, and macros simplifying common tasks - and now I don't need 80% of them.
But in 1.5 I've also found some issues:

- in previous Simbas you could drag a function name from the function list and drop it into the editor. It was very handy and efficient, so I'm missing this feature.
- there is a problem with the autocomplete window disappearing: when you write anything as a function argument, which has it's own autocomplete window (so anything with dot), then after you've written that argument there is no longer autocomplete window for the initial function.
E.x. While writing this code it's initially showing autocomplete window for  clickmouse(). But after you type "P."  window for TPoint pops up. And after you've finished typing "P.x" you don't see autosomplete window anymore. I think autocomplete for "clickmouse" should return back.  
```
var p :Tpoint;
begin
  clickmouse( P.x , P.y , 1);
end.        
```

- It's missing "clear debug box" icon, please add it back. It was practical, it was handy for debugging, I've been using it a lot.

Cheers and thanks for keeping Simba alive.

**Comment by slackydev** [comment]
Regarding your last point, the "clear debug box" is now the trash-can icon 
![image](https://user-images.githubusercontent.com/1329664/220177167-c4e55ce5-950c-4ffd-88ab-f6a9b5f047a5.png)

**Comment by ollydev** [comment]
Feel free to try the latest 1500 builds. Everything should be fixed.
https://github.com/Villavu/Simba-Build-Archive
