### ISSUE TITLE
Target Selector Won't Drag, Mac

### ISSUE THREAD

**Issue by Wozzify** [MerlijnWajer/Simba#511]
Hello,

So after building SIMBA for the ARM Mac spec, I have everything setup nicely, but cannot target selector drag anywhere, if I click and drag it just acts as if it has only been clicked, there is no draggable feature that I have experienced on windows.

Message in box is : 
`Window Selected: 0
 - Dimensions: 0x0
 - Title: ""
 - Class: ""
 - PID: 0 (64 bit)
 - Executable: ""`

Has anyone managed to get it draggable/attachable to client ?

Thanks,

**Comment by ollydev** [comment]
Fixed. 
Simba is barely tested on MacOS but I have a VM (terrible experience lol).

I did just find out that returning window image when using hi-dpi display is broken and Show(Image) seems to be broken too.
Will get around to that soon.
