### ISSUE TITLE
Building on mac M1

### ISSUE THREAD

**Issue by Moeinich** [MerlijnWajer/Simba#512]
trying to build this on M1 mac, I do have installed libffi via brew, but I am getting this when trying to compile for MACOS-AARCH64:
![SCR-20231110-lctc](https://github.com/Villavu/Simba/assets/5568731/b4f0a2f8-2b21-4ab6-ac75-cb998f60ed57)

same error for MACOS64

**Comment by ollydev** [comment]
I think you need Lazarus 3.0 RC2
https://sourceforge.net/projects/lazarus/files/Lazarus%20macOS%20x86-64/Lazarus%203.0RC2/

If unware there are aarch64 binaries here https://github.com/Villavu/Simba-Build-Archive though quite untested.
