### ISSUE TITLE
FindTextTPAInTPA not always working

### ISSUE THREAD

**Issue by cohenadair** [MerlijnWajer/Simba#75]
I'm guessing it has something to do with the height of the text and the text I'm trying to find has lines really close together, but hopefully it can be changed to work in that kind of situation.

http://img687.imageshack.us/img687/1077/20780891.png -- I'm trying to find thirst in all that text, and FindTextTPAInTPA returns false.  It'll work for 'll' or 'attern', but any variation of thirst and dehydrate don't work (which are the ones I need).

Testing with this code:
http://paste.villavu.com/show/e8onjyom4EWkJOj2cMwh/

I was going to write a countColor alternative, but I figure you'd rather have it reported.

**Comment by JohnPeel** [comment]
@cohenadair Any updates?

**Comment by cohenadair** [comment]
@JohnPeel haha 4 years later...

No, definitely not updates that I can recall.

**Comment by JohnPeel** [comment]
@cohenadair, I'm assuming this is just a limitation of the function, and not actually a bug. Is a better function still needed? or has a solution been found?

I cannot see the example image, seems to have gone down.

**Comment by cohenadair** [comment]
@JohnPeel 

If it hasn't become a bigger issue since it was reported I think it's probably fine.  I don't really remember, but I think it was having trouble because some letters were overlapping with letters from the line above or below.  In that case I think it's just a limitation of the function, and failsafes should be used to handle these situations.

**Comment by JohnPeel** [comment]
Thanks for the reply, I'm gonna close the issue then. =)
